export enum LogTypes {
	SIGNIN = 'SIGNIN',
	COOKIE_SIGNIN = 'COOKIE_SIGNIN',
	NOT_SIGNED_IN = 'NOT_SIGNED_IN',
  SIGNOUT = 'SIGNOUT',
  ROUTE_CHANGE = 'ROUTE_CHANGE',
  ERROR = 'ERROR',
  LANGUAGE_CHANGE = 'LANGUAGE_CHANGE',
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS'
}
