export enum SignInStatus {
	NOT_SIGNED_IN_YET = 'NOT_SIGNED_IN_YET',
	SIGN_IN_ERROR = 'SIGN_IN_ERROR',
  SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS',
  SIGN_IN_SUCCESS_BY_COOKIE = 'SIGN_IN_SUCCESS_BY_COOKIE',
  SIGN_OUT_ERROR = 'SIGN_OUT_ERROR',
  SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
}